### ISSUE TITLE
Error retrieving Keycloak token

### ISSUE THREAD

**Issue by fab-codes** [nicolabeghin/keycloak-spid-provider-configuration-client#6]
Hi, my Keycloak version is 23.0.0 and I need to integrate login with SPID.
When I run the client the output is:

![image](https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client/assets/53128434/dabcf33f-b41f-476a-80de-f23d5e39d49c)

I configured my .env file with right Realm and `createSpidDemoIdP = true`

Does anyone know what it might be related to? I also tried with version 23.0.6 but same story.

Thanks!

**Comment by JackAubrey** [comment]
Hi. I'm not a specialist, but spending a bit of time through Keycloak doc and inspecting this code (I never worked with nodes.js until now) I found where is the main issue.

KeyCloak 24.X removed the prefix "/auth" from its REST API.

So simply modify the "https.js" file in order to remove the "/auth" from all URL occurrence.

**Comment by fab-codes** [comment]
Ooh ok, it worked. Thank you so much!
