### ISSUE TITLE
Error importing IdP configuration from metadata

### ISSUE THREAD

**Issue by dwige3** [nicolabeghin/keycloak-spid-provider-configuration-client#7]
Hi, my Keycloak version is 23.0.6 and I need to integrate login with SPID.
When I run **npm create-idps** the output is:

![idps](https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client/assets/28624168/77499b0a-406f-4833-a4a1-09c010449619)

i configure my .env:
 # local spid
**createSpidTestIdP = true
spidTestIdPAlias = spid-saml-check
spidTestIdPMetadataURL = https://localhost:8443/metadata.xml**
please give me some solutions.
Thanks

**Comment by matteofregiari** [comment]
Have you solved? I've the same error @dwige3

**Comment by JackAubrey** [comment]
Hi Matteo. I had the same problem.
I was forced to work around the problem in the following way. Given that I use Linux.

- install "thttpd"
- create a folder and go inside
- save the metadata obtained from "https://localhost:8443/metadata.xml" into the created folder
- run "thttp" in this manner:  thttpd -p 8001 -d .
- check if metadata is reachable: "http://localhost:8001/metadata.xml"
- modify the ".env" using the new url location
- rerun the config script.

**Comment by fab-codes** [comment]
Hi guys, I had the same problem.
I tried JackAubrey's solution (with apache2 instead of thttpd), but I still have the same problem...

![image](https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client/assets/53128434/d4075e39-9efa-43ed-80dc-9c5f8f47650c)

I use Windows 11.
I'm trying to repeat the procedure on a VM with some Linux dist, but I don't think it makes sense.

Has anyone else encountered the same error?

UPDATE: I solved this problem by replacing localhost with WSL IP Address!

**Comment by nicolabeghin** [comment]
The error is most probably coming from Keycloak not able to access the provided metadata XML - if using a dockerized Keycloak, localhost is considered Keycloak's container localhost. For this reason, it's suggested to avoid using localhost in favor of a locally accessible LAN IP address (like 192.168.1.1 or similar) like @FabrizioGreco did

**Comment by JackAubrey** [comment]
@FabrizioGreco I forgot another important thing. Since I was creating a VM used to test code, I solved this problem running keycloak in dev mode disabling so the HTTPS. Also I rebuilt saml-check in order to disable the https support.

I could describe here (step by step) all my workarounds but these are thought for a dev environment. NOT for PR.

**Comment by fab-codes** [comment]
Thank you for your comment @JackAubrey! I have already solved the issue, so I don't need the instructions at the moment. However, if it's not too much trouble, could you still describe the steps you followed? They might be helpful for others in the same situation.

Thank you very much!

**Comment by JackAubrey** [comment]
@FabrizioGreco It's absolutely not a problem. I've already did it many times for my team :)
My env is a VM with a fresh installation of Fedora.
**These instructions are NOT thought for production environments.**

I have Keycloak installed into the VM so this means I never refer to it via "localhost" but using its IP that in this case is tipically "172.17.0.1"

The "spid-saml-check" wil run in a docker container inside the same VM

1 first of all I have disabled the Keycloak HTTPS support and CHANGED its port because also spid-saml-check run using the  port 8443 yet.
This is my keycloak.service file
Environment="KC_PROXY=edge"
Environment="KC_HTTP_ENABLED=true"
Environment="KC_HOSTNAME_STRICT=false"
Environment="KC_HOSTNAME_STRICT_HTTPS=false"
ExecStartPre=/opt/keycloak/bin/kc.sh build
ExecStart=/opt/keycloak/bin/kc.sh start --https-port=8080


2 Disable SSL support on spid-saml-check
- clone from github spid-saml-check
- modify the Docker file in order to modify the entrypoint:  
**ENTRYPOINT cd spid-validator && npm config set strict-ssl false && npm run start-prod**
- build the image: **docker build -t spid-saml-check .**
- run it: docker run --name spid-saml-check -d -t -i  -p 8443:8443 spid-saml-check
- verify spid-saml-check is reachable: https://localhost:8443/metadata.xml
- save the XML in a folder where you'll run "thttpd"

3 use "thttpd" 
- install "thttpd" if you haven't
- goto the folder where you saved the metadata.xml
- from this path type: 
$  thttpd -p 8001 -d .
- in a browser verify if file is served: http://localhost:8001/metadata.xml

4 spid-provider-configuration-client
- clone the project
- configure the ".env" file in this manner

keycloakServerBaseURL=http://172.17.0.1:8080

createSpidTestIdP = true
spidTestIdPAlias = spid-saml-check
spidTestIdPMetadataURL = http://localhost:8001/metadata.xml

- now fix the "auth" prefix
find . -type f -name "http.js" -exec sed -i -e 's@/auth/@/@g' {} +

- now fix the flow case
find . -type f -name "*.json" -exec sed -i -e 's/first broker login (SPID)/First Broker Login (SPID)/g' {} +

- ensure the "log" folder exists
mkdir log

- now run manually the npm commands without make the image
npm cache clean --force
npm install
npm run create-realm
npm run create-idps

**Comment by JackAubrey** [comment]
PS In order to do not disable the keycloak HTTPS, following the instruction provided by a colleague I have put keycloak behind an haproxy where I have configured a valid cert.

This approach is better but its configuration is not easy and too long.
